channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.3.1
- pip:
  - mlflow==2.17.2
  - brotli==1.1.0
  - click==8.1.7
  - cloudpickle==3.1.0
  - h2==4.1.0
  - openai==1.54.4
  - pygments==2.18.0
  - zstandard==0.23.0
name: mlflow-env
